name: Deploy

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: |
        docker build -t docker.pkg.github.com/pavel-the-best/merger-bot/merger-bot:latest .
    - name: Upload docker image
      run: |
        docker login --username pavel-the-best --password ${{ secrets.PKG_REGISTRY_TOKEN }} docker.pkg.github.com
        docker push docker.pkg.github.com/pavel-the-best/merger-bot/merger-bot:latest
